spring.application.name: uploder-service

server.servlet.context-path: /uploads
server.port: 9050

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

cloudinary:
  cloud-name: dwnzjrmh
  api-key: 675455273434252
  api-secret: mtQoVdqmFuiC5mBPDZUuMeyvPuc


